version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - /docker/certs:/etc/nginx/certs:ro
     - /etc/nginx/vhost.d
     - /usr/share/nginx/html
    labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - /docker/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy:rw 

  mongo:
    container_name: mongo
    build: ./bin/mongo/
    expose: 
      - "27017"
    volumes:
      - /docker/veinte/data:/data/db
     
  app:
    container_name: nodeVeinte
    build: .
    restart: always
    # environment: 
    #   NODE_ENV: development
    environment: 
     - VIRTUAL_HOST=coindor.ddnsking.com
     - VIRTUAL_PORT=3000
     - LETSENCRYPT_HOST=coindor.ddnsking.com
     - LETSENCRYPT_EMAIL=jorge.riera9@gmail.com
    depends_on: 
      - mongo
    ports: 
      - 3000:3000
    links: 
      - mongo
